name: Update All Flake Inputs

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  update-flake-lock:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Install Determinate Nix
        uses: DeterminateSystems/determinate-nix-action@v3
      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@main
        with:
          pr-title: "Update Everything"
          token: ${{ secrets.NIX_UPDATE_FLAKE_LOCK_ACTION }}
          branch: update-everything-action
          git-author-name: Github Actions
          git-author-email: github-actions[bot]@users.noreply.github.com
          git-committer-name: Daniel Gafni
          git-committer-email: danielgafni16@gmail.com
          pr-assignees: danielgafni
          sign-commits: true
          gpg-private-key: ${{ secrets.NIX_FLAKE_UPDATE_GPG_PRIVATE_KEY }}
          gpg-passphrase: ${{ secrets.NIX_FLAKE_UPDATE_GPG_PASSPHRASE }}
          pr-labels: |
            dependencies
            automated
